name = "website-analyzer"
compatibility_date = "2024-03-15"

# Set the main entry file directly
main = "dist/index.mjs"

[build]
command = "npm run build"

workers_dev = true

[limits]
memory = "128MB"
cpu_ms = 50

[[kv_namespaces]]
binding = "ANALYZER_CACHE"
id = "real-kv-namespace-id"
preview_id = "real-preview-namespace-id"

[vars]
PYODIDE_VERSION = "0.25.0"
ENABLE_CACHING = "true"
CACHE_TTL = "3600"
